--- 
- name: installs fail2ban on ansible hosts
  hosts: fail2ban-hosts
  become: yes
  tasks:
  
  - name: install apt fail2ban packages
    apt: 
      name: "{{ item }}"   
      state: latest
      update_cache: yes
      cache_valid_time: 3600
    with_items:
      - fail2ban
      - sendmail
  
  - name: override the basic fail2ban configuration with .local file
    copy:
      src: jail.local
      dest: /etc/fail2ban/jail.local
      owner: root
      group: root
      mode: 0644
