---
- hosts: webservers

  tasks:
   - name: Install tar
     apt: name={{ tar }} update_cache=yes state=latest
     loop: [ 'tar.gz' ] 

   - name: Extract foo.tgz into /var/lib/foo
     ansible.builtin.unarchive:
       src: foo.tgz
       dest: /var/lib/foo

   - name: Unarchive a file that is already on the remote machine
     ansible.builtin.unarchive:
       src: /tmp/foo.zip
       dest: /usr/local/bin
       remote_src: yes

   - name: Unarchive a file that needs to be downloaded (added in 2.0
     ansible.builtin.unarchive:
       src: https://example.com/example.zip
       dest: /usr/local/bin
       remote_src: yes

   - name: Unarchive a file with extra options
     ansible.builtin.unarchive:
       src: /tmp/foo.zip
       dest: /usr/local/bin
       extra_opts:
       - --transform
       - s/^xxx/yyy/
