---
- hosts: all
  user: root

- name: Setup | authorized key upload
    authorized_key: user={{ createuser }}
      key="{{ lookup('file', 'mypublickey.pub') }}
      path='/home/{{ createuser }}/.ssh/authorized_keys'
      manage_dir=no
    sudo: true

 - name: Allow all access to tcp port 22
   community.general.ssh:
     rule: allow
     port: '22'
     proto: tcp

  - name: Disable Password Authentication
       lineinfile:
           dest=/etc/ssh/sshd_config
           regexp='^PasswordAuthentication'
           line="PasswordAuthentication no"
           state=present
           backup=yes
 
 - name : Disable Root Login
      lineinfile :
           dest=/etc/ssh/sshd_config
           regexp='^PermitRootLogin'
           line="PermitRootLogin no"
           state=present
           backup=yes
     notify :
       - restart ssh
